In [2]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn import tree

In [1]:
import pandas as pd
data= pd.read_csv('titanic.csv')
data.head()

Unnamed: 0  Survived  Pclass  \
0           0         0       3   
1           1         1       1   
2           2         1       3   
3           3         1       1   
4           4         0       3   

                                                Name     Sex   Age  \
0                            Braund, Mr. Owen Harris    male  22.0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
2                             Heikkinen, Miss. Laina  female  26.0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
4                           Allen, Mr. William Henry    male  35.0   

   Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0                        1                        0   7.2500  
1                        1                        0  71.2833  
2                        0                        0   7.9250  
3                        1                        0  53.1000  
4                        0                        0   8.0500

In [4]:
x=data[['Age','Fare']]
y=data['Survived']
print(x.shape,y.shape)

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=100)
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(891, 2) (891,)
(712, 2) (179, 2) (712,) (179,)


In [8]:
from joblib import dump, load
model = load('custom_rf.joblib')

In [9]:
model.predict([[25,50]]) # age,fare

array([1], dtype=int64)

In [10]:
model.predict([[1.8,50]]) # age,fare

array([0], dtype=int64)

In [11]:
model.predict([[1.8,50],[80,100]]) # age,fare

array([0, 0], dtype=int64)